name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_icons: ^1.1.0
  sms_autofill: ^2.2.0
  provider: ^6.0.3
  google_fonts: ^3.0.1
  pin_code_fields: ^7.4.0
  intl_phone_field: ^3.1.0
  flutter_spinwheel: ^0.1.0
  flutter_fortune_wheel: ^1.2.0
  basic_utils: ^4.5.0
  flutter_spinning_wheel: ^1.1.0
  rxdart: ^0.27.5
  font_awesome_flutter: ^10.1.0
  dio: ^4.0.6
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  quantity_input: ^1.0.2
  pay: ^1.0.10
  image_picker: ^0.8.5+3
  flutter_dialogs: ^3.0.0
  youtube_player_flutter: ^8.1.0
  flutter_secure_storage: ^5.1.0
  curved_navigation_bar: ^1.0.3
  booking_calendar: ^1.1.4
  flutter_html: ^3.0.0-alpha.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
